document.addEventListener('DOMContentLoaded', () => {
  const languageDropdown = document.getElementById('language-dropdown');
  const languageSelectedButton = document.getElementById('language-selected');
  const languageOptions = document.querySelectorAll('.language-option');
  const categoryButtons = document.querySelectorAll('.category-button');
  const display = document.getElementById('menu-items-display');

  let currentLang = 'tr';
  let currentCategory = 'breakfast';

  function updateLanguageSelection(lang) {
    currentLang = lang;
    const selectedOption = document.querySelector(`.language-option[data-lang="${lang}"]`);
    if (!selectedOption) return;
    const label = selectedOption.dataset.label;
    const flagSrc = selectedOption.querySelector('.flag-img')?.getAttribute('src');
    languageSelectedButton.querySelector('.selected-language').textContent = label;
    if (flagSrc) languageSelectedButton.querySelector('.selected-flag').setAttribute('src', flagSrc);

    languageOptions.forEach(opt => opt.classList.toggle('active', opt.dataset.lang === lang));
  }

  const menu = [
    // BREAKFAST
    { category: 'breakfast', name: {tr: 'Türk Kahvaltısı', en: 'Turkish Breakfast', ru: 'Турецкий завтрак', dk: 'Tyrkisk morgenmad', fi: 'Turkkilainen aamiainen', se: 'Turkisk frukost', no: 'Tyrkisk frokost', nl: 'Turks ontbijt', de: 'Türkisches Frühstück'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'breakfast', name: {tr: 'İngiliz Kahvaltısı', en: 'English Breakfast', ru: 'Английский завтрак', dk: 'Engelsk morgenmad', fi: 'Englantilainen aamiainen', se: 'Engelsk frukost', no: 'Engelsk frokost', nl: 'Engels ontbijt', de: 'Englisches Frühstück'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'breakfast', name: {tr: 'Türk Omlet Kahvaltısı', en: 'Turkish Omelette Breakfast', ru: 'Турецкий омлет завтрак', dk: 'Tyrkisk omelet morgenmad', fi: 'Turkkilainen omelettiaamiainen', se: 'Turkisk omelettfrukost', no: 'Tyrkisk omelettfrokost', nl: 'Turks omeletontbijt', de: 'Türkisches Omelett-Frühstück'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'breakfast', name: {tr: 'Salamlı Tost', en: 'Salami Toast', ru: 'Тост с салями', dk: 'Salami Toast', fi: 'Salami Toast', se: 'Salami Toast', no: 'Salami Toast', nl: 'Salami Toast', de: 'Salami Toast'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'breakfast', name: {tr: 'Peynirli Tost', en: 'Cheese Toast', ru: 'Тост с сыром', dk: 'Ost Toast', fi: 'Juusto Toast', se: 'Ost Toast', no: 'Ost Toast', nl: 'Kaas Toast', de: 'Käse Toast'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'breakfast', name: {tr: 'Karışık Tost', en: 'Combo Toast', ru: 'Смешанный тост', dk: 'Kombo Toast', fi: 'Combo Toast', se: 'Kombinerad Toast', no: 'Kombinasjon Toast', nl: 'Combi Toast', de: 'Kombi Toast'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'breakfast', name: {tr: 'Sade Omlet', en: 'Plain Omelette', ru: 'Обычный омлет', dk: 'Almindelig Omelet', fi: 'Tavallinen Omeletti', se: 'Naturell Omelett', no: 'Naturell Omelett', nl: 'Naturel Omelet', de: 'Natur Omelett'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'breakfast', name: {tr: 'Peynirli Omlet', en: 'Cheese Omelette', ru: 'Омлет с сыром', dk: 'Ost Omelet', fi: 'Juusto Omeletti', se: 'Ost Omelett', no: 'Ost Omelett', nl: 'Kaas Omelet', de: 'Käse Omelett'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'breakfast', name: {tr: 'Mantarlı Omlet', en: 'Mushroom Omelette', ru: 'Омлет с грибами', dk: 'Svampe Omelet', fi: 'Sieni Omeletti', se: 'Svamp Omelett', no: 'Sopp Omelett', nl: 'Champignon Omelet', de: 'Pilz Omelett'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'breakfast', name: {tr: 'Salamlı Omlet', en: 'Salami Omelette', ru: 'Омлет с салями', dk: 'Salami Omelet', fi: 'Salami Omeletti', se: 'Salami Omelett', no: 'Salami Omelett', nl: 'Salami Omelet', de: 'Salami Omelett'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'breakfast', name: {tr: 'Jambonlu Omlet', en: 'Ham Omelette', ru: 'Омлет с ветчиной', dk: 'Ham Omelet', fi: 'Ham Omeletti', se: 'Ham Omelett', no: 'Ham Omelett', nl: 'Ham Omelet', de: 'Ham Omelett'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'breakfast', name: {tr: 'Pastırmalı Omlet', en: 'Bacon Omelette', ru: 'Омлет с беконом', dk: 'Bacon Omelet', fi: 'Pekoni Omeletti', se: 'Bacon Omelett', no: 'Bacon Omelett', nl: 'Spek Omelet', de: 'Speck Omelett'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'breakfast', name: {tr: 'Karışık Omlet', en: 'Mixed Omelette', ru: 'Смешанный омлет', dk: 'Blandet Omelet', fi: 'Sekoitettu Omeletti', se: 'Blandad Omelett', no: 'Blandet Omelett', nl: 'Gemengd Omelet', de: 'Gemischt Omelett'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },

    // STARTERS
    { category: 'starters', name: {tr: 'Nachos', en: 'Nachos', ru: 'Начос', dk: 'Nachos', fi: 'Nachos', se: 'Nachos', no: 'Nachos', nl: 'Nachos', de: 'Nachos'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'starters', name: {tr: 'Tavuk Sepeti & Patates', en: 'Chicken Basket & Chips', ru: 'Куриная корзина и фри', dk: 'Kyllingkurv & pommes frites', fi: 'Kanasetti & ranskalaiset', se: 'Kycklingkorg & pommes frites', no: 'Kyllingkurv & pommes frites', nl: 'Kipmand & frietjes', de: 'Hähnchenkorb & Pommes'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'starters', name: {tr: 'Domates Çorbası', en: 'Tomato Soup', ru: 'Томатный суп', dk: 'Tomat Suppe', fi: 'Tomaatti Keitto', se: 'Tomat Soppa', no: 'Tomat Suppe', nl: 'Tomaat Soep', de: 'Tomate Suppe'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'starters', name: {tr: 'Mercimek Çorbası', en: 'Lentil Soup', ru: 'Чечевичный суп', dk: 'Linse Suppe', fi: 'Linssi Keitto', se: 'Linser Soppa', no: 'Linser Suppe', nl: 'Linzen Soep', de: 'Linsen Suppe'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'starters', name: {tr: 'Tavuk Çorbası', en: 'Chicken Soup', ru: 'Куриный суп', dk: 'Kylling Suppe', fi: 'Kana Keitto', se: 'Kyckling Soppa', no: 'Kylling Suppe', nl: 'Kip Soep', de: 'Hähnchen Suppe'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'starters', name: {tr: 'Mantar Çorbası', en: 'Mushroom Soup', ru: 'Грибной суп', dk: 'Svampe Suppe', fi: 'Sieni Keitto', se: 'Svamp Soppa', no: 'Sopp Suppe', nl: 'Champignon Soep', de: 'Pilz Suppe'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'starters', name: {tr: 'Peynirli Salata', en: 'Cheese Salad', ru: 'Салат с сыром', dk: 'Ost Salat', fi: 'Juusto Salaatti', se: 'Ost Sallad', no: 'Ost Salat', nl: 'Kaas Salade', de: 'Käse Salat'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'starters', name: {tr: 'Sezar Salata', en: 'Caesar Salad', ru: 'Салат Цезарь', dk: 'Caesar Salat', fi: 'Caesar Salaatti', se: 'Caesar Sallad', no: 'Caesar Salat', nl: 'Caesar Salade', de: 'Caesar Salat'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'starters', name: {tr: 'Tavuklu Salata', en: 'Chicken Salad', ru: 'Салат с курицей', dk: 'Kylling Salat', fi: 'Kana Salaatti', se: 'Kyckling Sallad', no: 'Kylling Salat', nl: 'Kip Salade', de: 'Hähnchen Salat'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'starters', name: {tr: 'Karidesli Salata', en: 'Shrimp Salad', ru: 'Салат с креветками', dk: 'Reje Salat', fi: 'Katkarapu Salaatti', se: 'Räka Sallad', no: 'Reke Salat', nl: 'Garnalen Salade', de: 'Garnelen Salat'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'starters', name: {tr: 'Karışık Salata', en: 'Mixed Salad', ru: 'Смешанный салат', dk: 'Blandet Salat', fi: 'Sekoitettu Salaatti', se: 'Blandad Sallad', no: 'Blandet Salat', nl: 'Gemengd Salade', de: 'Gemischt Salat'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'starters', name: {tr: 'Ton Balıklı Salata', en: 'Tuna Salad', ru: 'Салат с тунцом', dk: 'Tun Salat', fi: 'Tonnikala Salaatti', se: 'Tonfisk Sallad', no: 'Tunfisk Salat', nl: 'Tonijn Salade', de: 'Thunfisch Salat'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'starters', name: {tr: 'Yeşil Salata', en: 'Green Salad', ru: 'Зеленый салат', dk: 'Grøn Salat', fi: 'Vihreä Salaatti', se: 'Grön Sallad', no: 'Grønn Salat', nl: 'Groen Salade', de: 'Grün Salat'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },

    // BURGERS (SANDWICHES & BURGERS)
    { category: 'burgers', name: {tr: 'Peynirli Sandviç', en: 'Cheese Sandwich', ru: 'Сэндвич с сыром', dk: 'Ostesandwich', fi: 'Juustosämpylä', se: 'Ostsmörgås', no: 'Ostesandwich', nl: 'Kaassandwich', de: 'Käsesandwich'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'burgers', name: {tr: 'Salamlı Sandviç', en: 'Salami Sandwich', ru: 'Сэндвич с салями', dk: 'Salamisandwich', fi: 'Salamisämpylä', se: 'Salamisandwich', no: 'Salamisandwich', nl: 'Salami sandwich', de: 'Salami-Sandwich'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'burgers', name: {tr: 'Karışık Sandviç', en: 'Combo Sandwich', ru: 'Комбо сэндвич', dk: 'Kombosandwich', fi: 'Komboleipä', se: 'Kombosandwich', no: 'Kombosandwich', nl: 'Combi sandwich', de: 'Kombi-Sandwich'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'burgers', name: {tr: 'Hamburger', en: 'Hamburger', ru: 'Гамбургер', dk: 'Hamburger', fi: 'Hamburger', se: 'Hamburger', no: 'Hamburger', nl: 'Hamburger', de: 'Hamburger'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'burgers', name: {tr: 'Cheeseburger', en: 'Cheese Burger', ru: 'Чизбургер', dk: 'Ost Burger', fi: 'Juusto Burger', se: 'Ost Burger', no: 'Ost Burger', nl: 'Kaas Burger', de: 'Käse Burger'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'burgers', name: {tr: 'Double Beach Burger', en: 'Double Beach Burger', ru: 'Дабл Бич Бургер', dk: 'Double Beach Burger', fi: 'Double Beach Burger', se: 'Double Beach Burger', no: 'Double Beach Burger', nl: 'Double Beach Burger', de: 'Double Beach Burger'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'burgers', name: {tr: 'Çıtır Tavuk Burger', en: 'Crispy Chicken Burger', ru: 'Хрустящий куриный бургер', dk: 'Crispy Kylling Burger', fi: 'Crispy Kana Burger', se: 'Crispy Kyckling Burger', no: 'Crispy Kylling Burger', nl: 'Crispy Kip Burger', de: 'Crispy Hähnchen Burger'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'burgers', name: {tr: 'Meksika Burger', en: 'Mexican Burger', ru: 'Мексиканский бургер', dk: 'Mexicansk Burger', fi: 'Meksikolainen Burger', se: 'Mexikansk Burger', no: 'Meksikansk Burger', nl: 'Mexicaans Burger', de: 'Mexikanisch Burger'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'burgers', name: {tr: 'Et Roll', en: 'Meat Roll', ru: 'Мясной ролл', dk: 'Kød Roll', fi: 'Liha Roll', se: 'Kött Roll', no: 'Kjøtt Roll', nl: 'Vlees Roll', de: 'Fleisch Roll'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'burgers', name: {tr: 'Tavuk Roll', en: 'Chicken Roll', ru: 'Куриный ролл', dk: 'Kylling Roll', fi: 'Kana Roll', se: 'Kyckling Roll', no: 'Kylling Roll', nl: 'Kip Roll', de: 'Hähnchen Roll'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'burgers', name: {tr: 'Tavuk Wrap', en: 'Chicken Wrap', ru: 'Куриный врап', dk: 'Kyllingewrap', fi: 'Kanaswrap', se: 'Kycklingwrap', no: 'Kyllingwrap', nl: 'Kipwrap', de: 'Hähnchen-Wrap'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'burgers', name: {tr: 'Patates Kızartması', en: 'Chips', ru: 'Картофель фри', dk: 'Chips', fi: 'Chips', se: 'Chips', no: 'Chips', nl: 'Chips', de: 'Chips'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },

    // PASTAS
    { category: 'pasta', name: {tr: 'Spagetti Bolonez', en: 'Spaghetti Bolognese', ru: 'Спагетти Болоньезе', dk: 'Spaghetti Bolognese', fi: 'Spaghetti Bolognese', se: 'Spaghetti Bolognese', no: 'Spaghetti Bolognese', nl: 'Spaghetti Bolognese', de: 'Spaghetti Bolognese'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pasta', name: {tr: 'Spagetti Karbonara', en: 'Spaghetti Carbonara', ru: 'Спагетти Карбонара', dk: 'Spaghetti Carbonara', fi: 'Spaghetti Carbonara', se: 'Spaghetti Carbonara', no: 'Spaghetti Carbonara', nl: 'Spaghetti Carbonara', de: 'Spaghetti Carbonara'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pasta', name: {tr: 'Spagetti Napoliten', en: 'Spaghetti Napolitana', ru: 'Спагетти Наполитана', dk: 'Spaghetti Napolitana', fi: 'Spaghetti Napolitana', se: 'Spaghetti Napolitana', no: 'Spaghetti Napolitana', nl: 'Spaghetti Napolitana', de: 'Spaghetti Napolitana'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pasta', name: {tr: 'Penne Arrabbiata', en: 'Penne Arrabbiata', ru: 'Пенне Арраббиата', dk: 'Penne Arrabbiata', fi: 'Penne Arrabbiata', se: 'Penne Arrabbiata', no: 'Penne Arrabbiata', nl: 'Penne Arrabbiata', de: 'Penne Arrabbiata'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pasta', name: {tr: 'Penne Al Tono', en: 'Penne Al Tono', ru: 'Пенне Аль Тоно', dk: 'Penne Al Tono', fi: 'Penne Al Tono', se: 'Penne Al Tono', no: 'Penne Al Tono', nl: 'Penne Al Tono', de: 'Penne Al Tono'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pasta', name: {tr: 'Pastırmalı Penne', en: 'Penne With Bacon', ru: 'Пенне с беконом', dk: 'Penne With Bacon', fi: 'Penne With Pekoni', se: 'Penne With Bacon', no: 'Penne With Bacon', nl: 'Penne With Spek', de: 'Penne With Speck'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pasta', name: {tr: 'Tavuklu Penne', en: 'Penne With Chicken', ru: 'Пенне с курицей', dk: 'Penne With Kylling', fi: 'Penne With Kana', se: 'Penne With Kyckling', no: 'Penne With Kylling', nl: 'Penne With Kip', de: 'Penne With Hähnchen'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pasta', name: {tr: 'Güveçte Lazanya', en: 'Lasagne In Casserole', ru: 'Лазанья в горшочке', dk: 'Lasagne In Casserole', fi: 'Lasagne In Casserole', se: 'Lasagne In Casserole', no: 'Lasagne In Casserole', nl: 'Lasagne In Casserole', de: 'Lasagne In Casserole'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },

    // MAIN DISHES (ANA YEMEKLER)
    { category: 'main-dishes', name: {tr: 'Chicken Americano', en: 'Chicken Americano', ru: 'Курица Американо', dk: 'Kylling Americano', fi: 'Kana Americano', se: 'Kyckling Americano', no: 'Kylling Americano', nl: 'Kip Americano', de: 'Hähnchen Americano'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Tatlı Ekşi Tavuk', en: 'Chicken Sweet & Sour', ru: 'Курица в кисло-сладком соусе', dk: 'Kylling Sweet & Sour', fi: 'Kana Sweet & Sour', se: 'Kyckling Sweet & Sour', no: 'Kylling Sweet & Sour', nl: 'Kip Sweet & Sour', de: 'Hähnchen Sweet & Sour'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Izgara Tavuk', en: 'Grill Chicken', ru: 'Курица на гриле', dk: 'Grill Kylling', fi: 'Grilli Kana', se: 'Grill Kyckling', no: 'Grill Kylling', nl: 'Grill Kip', de: 'Grill Hähnchen'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Tavuk Şiş', en: 'Chicken Shish', ru: 'Куриный шашлык', dk: 'Kylling Shish', fi: 'Kana Shish', se: 'Kyckling Shish', no: 'Kylling Shish', nl: 'Kip Shish', de: 'Hähnchen Shish'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Köri Soslu Tavuk', en: 'Chicken Curry', ru: 'Курица карри', dk: 'Kylling Karry', fi: 'Kana Currykastike', se: 'Kyckling Curry', no: 'Kylling Curry', nl: 'Kip Curry', de: 'Hähnchen Curry'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Meksika Usulü Tavuk', en: 'Chicken Mexican', ru: 'Курица по-мексикански', dk: 'Kylling Mexicansk', fi: 'Kana Meksikolainen', se: 'Kyckling Mexikansk', no: 'Kylling Meksikansk', nl: 'Kip Mexicaans', de: 'Hähnchen Mexikanisch'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Sarımsaklı Tavuk', en: 'Garlic Chicken', ru: 'Чесночная курица', dk: 'Hvidløg Kylling', fi: 'Valkosipuli Kana', se: 'Vitlök Kyckling', no: 'Hvitløk Kylling', nl: 'Knoflook Kip', de: 'Knoblauch Hähnchen'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Karabiberli Tavuk', en: 'Pepred Chicken', ru: 'Курица с перцем', dk: 'Pepred Kylling', fi: 'Pepred Kana', se: 'Pepred Kyckling', no: 'Pepred Kylling', nl: 'Pepred Kip', de: 'Pepred Hähnchen'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Chicken Bearnaise', en: 'Chicken Bearnaise', ru: 'Курица под соусом Бернез', dk: 'Kylling Bearnaise', fi: 'Kana Bearnaise', se: 'Kyckling Bearnaise', no: 'Kylling Bearnaise', nl: 'Kip Bearnaise', de: 'Hähnchen Bearnaise'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Mantarlı Tavuk', en: 'Mushroom Chicken', ru: 'Курица с грибами', dk: 'Svampe Kylling', fi: 'Sieni Kana', se: 'Svamp Kyckling', no: 'Sopp Kylling', nl: 'Champignon Kip', de: 'Pilz Hähnchen'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Tavuk Şinitzel', en: 'Chicken Schnitzel', ru: 'Куриный шницель', dk: 'Kylling Schnitzel', fi: 'Kana Schnitzel', se: 'Kyckling Schnitzel', no: 'Kylling Schnitzel', nl: 'Kip Schnitzel', de: 'Hähnchen Schnitzel'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Tavuk Kanatları', en: 'Chicken Wings', ru: 'Куриные крылышки', dk: 'Kylling Wings', fi: 'Kana Wings', se: 'Kyckling Wings', no: 'Kylling Wings', nl: 'Kip Wings', de: 'Hähnchen Wings'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Chicken Hawaii', en: 'Chicken Hawaii', ru: 'Курица по-гавайски', dk: 'Kylling Hawaii', fi: 'Kana Hawaii', se: 'Kyckling Hawaii', no: 'Kylling Hawaii', nl: 'Kip Hawaii', de: 'Hähnchen Hawaii'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Tavuk Sote', en: 'Chicken Saute', ru: 'Куриное соте', dk: 'Kylling Saute', fi: 'Kana Saute', se: 'Kyckling Saute', no: 'Kylling Saute', nl: 'Kip Saute', de: 'Hähnchen Saute'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Barbekü Soslu Tavuk', en: 'Chicken Barbecue', ru: 'Курица барбекю', dk: 'Kylling Barbecue', fi: 'Kana Barbecue', se: 'Kyckling Barbecue', no: 'Kylling Barbecue', nl: 'Kip Barbecue', de: 'Hähnchen Barbecue'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Osmanlı Usulü Et', en: 'Meat Osmanli', ru: 'Мясо по-османски', dk: 'Kød Osmanli', fi: 'Liha Osmanli', se: 'Kött Osmanli', no: 'Kjøtt Osmanli', nl: 'Vlees Osmanli', de: 'Fleisch Osmanli'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Osmanlı Usulü Tavuk', en: 'Chicken Osmanli', ru: 'Курица по-османски', dk: 'Kylling Osmanli', fi: 'Kana Osmanli', se: 'Kyckling Osmanli', no: 'Kylling Osmanli', nl: 'Kip Osmanli', de: 'Hähnchen Osmanli'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Izgara Köfte', en: 'Grilled Meatballs', ru: 'Тефтели на гриле', dk: 'Grillet Meatballs', fi: 'Grillattu Meatballs', se: 'Grillad Meatballs', no: 'Grillet Meatballs', nl: 'Gegrild Meatballs', de: 'Gegrillt Meatballs'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Türk Kebabı', en: 'Turkish Kebab', ru: 'Турецкий кебаб', dk: 'Tyrkisk Kebab', fi: 'Turkkilainen Kebab', se: 'Turkisk Kebab', no: 'Tyrkisk Kebab', nl: 'Turks Kebab', de: 'Türkisch Kebab'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Tavuk Döner Kebap', en: 'Chicken Doner Kebab', ru: 'Куриный донер кебаб', dk: 'Kylling Döner Kebab', fi: 'Kana Döner Kebab', se: 'Kyckling Döner Kebab', no: 'Kylling Döner Kebab', nl: 'Kip Döner Kebab', de: 'Hähnchen Döner Kebab'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Et Döner Kebap', en: 'Meat Doner Kebab', ru: 'Мясной донер кебаб', dk: 'Kød Döner Kebab', fi: 'Liha Döner Kebab', se: 'Kött Döner Kebab', no: 'Kjøtt Döner Kebab', nl: 'Vlees Döner Kebab', de: 'Fleisch Döner Kebab'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Adana Kebap', en: 'Adana Kebab', ru: 'Адана кебаб', dk: 'Adana Kebab', fi: 'Adana Kebab', se: 'Adana Kebab', no: 'Adana Kebab', nl: 'Adana Kebab', de: 'Adana Kebab'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Tavuk Döner', en: 'Chicken Doner', ru: 'Куриный донер', dk: 'Kylling Döner', fi: 'Kana Döner', se: 'Kyckling Döner', no: 'Kylling Döner', nl: 'Kip Döner', de: 'Hähnchen Döner'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Köfte', en: 'Meatballs', ru: 'Котлеты', dk: 'Meatballs', fi: 'Meatballs', se: 'Meatballs', no: 'Meatballs', nl: 'Meatballs', de: 'Meatballs'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Dana Rosto', en: 'Beef Roast', ru: 'Ростбиф из говядины', dk: 'Beef Stege', fi: 'Beef Paistettu', se: 'Beef Rostad', no: 'Beef Stekt', nl: 'Beef Geroosterd', de: 'Beef Geröstet'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Karışık Izgara', en: 'Mixed Grill', ru: 'Гриль микс', dk: 'Blandet Grill', fi: 'Sekoitettu Grilli', se: 'Blandad Grill', no: 'Blandet Grill', nl: 'Gemengd Grill', de: 'Gemischt Grill'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Bonfile Steak', en: 'Fillet Steak', ru: 'Филе стейк', dk: 'Filet Bøf', fi: 'Filee Pihvi', se: 'Filé Stek', no: 'Filet Biff', nl: 'Filet Biefstuk', de: 'Filet Steak'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Biberli Steak', en: 'Pepper Steak', ru: 'Стейк с перцем', dk: 'Peber Bøf', fi: 'Pippuri Pihvi', se: 'Peppar Stek', no: 'Pepper Biff', nl: 'Peper Biefstuk', de: 'Pfeffer Steak'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Mantarlı Steak', en: 'Mushroom Steak', ru: 'Грибной стейк', dk: 'Svampe Bøf', fi: 'Sieni Pihvi', se: 'Svamp Stek', no: 'Sopp Biff', nl: 'Champignon Biefstuk', de: 'Pilz Steak'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Bearnaise Steak', en: 'Bearnaise Steak', ru: 'Стейк под соусом Бернез', dk: 'Bearnaise Bøf', fi: 'Bearnaise Pihvi', se: 'Bearnaise Stek', no: 'Bearnaise Biff', nl: 'Bearnaise Biefstuk', de: 'Bearnaise Steak'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Meksika Usulü Steak', en: 'Mexican Steak', ru: 'Мексиканский стейк', dk: 'Mexicansk Bøf', fi: 'Meksikolainen Pihvi', se: 'Mexikansk Stek', no: 'Meksikansk Biff', nl: 'Mexicaans Biefstuk', de: 'Mexikanisch Steak'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Soğanlı Steak', en: 'Onion Steak', ru: 'Стейк с луком', dk: 'Onion Bøf', fi: 'Onion Pihvi', se: 'Onion Stek', no: 'Onion Biff', nl: 'Onion Biefstuk', de: 'Onion Steak'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Plank Steak', en: 'Plank Steak', ru: 'Планк стейк', dk: 'Plank Bøf', fi: 'Plank Pihvi', se: 'Plank Stek', no: 'Plank Biff', nl: 'Plank Biefstuk', de: 'Plank Steak'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Wiener Schnitzel', en: 'Wiener Schnitzel', ru: 'Венский шницель', dk: 'Wiener Schnitzel', fi: 'Wiener Schnitzel', se: 'Wiener Schnitzel', no: 'Wiener Schnitzel', nl: 'Wiener Schnitzel', de: 'Wiener Schnitzel'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'main-dishes', name: {tr: 'Cordon Bleu', en: 'Cordon Bleu', ru: 'Кордон Блю', dk: 'Cordon Bleu', fi: 'Cordon Bleu', se: 'Cordon Bleu', no: 'Cordon Bleu', nl: 'Cordon Bleu', de: 'Cordon Bleu'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },

    // PIZZAS
    { category: 'pizzas', name: {tr: 'Groften Combo Pizza', en: 'Groften Combo Pizza', ru: 'Грофтен Комбо Пицца', dk: 'Groften Kombo Pizza', fi: 'Groften Combo Pizza', se: 'Groften Kombinerad Pizza', no: 'Groften Kombinasjon Pizza', nl: 'Groften Combi Pizza', de: 'Groften Kombi Pizza'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pizzas', name: {tr: 'Pizza Margherita', en: 'Pizza Margherita', ru: 'Пицца Маргарита', dk: 'Pizza Margherita', fi: 'Pizza Margherita', se: 'Pizza Margherita', no: 'Pizza Margherita', nl: 'Pizza Margherita', de: 'Pizza Margherita'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pizzas', name: {tr: 'Pizza Hawaiian', en: 'Pizza Hawaiian', ru: 'Пицца Гавайская', dk: 'Pizza Hawaii', fi: 'Pizza Hawaii', se: 'Pizza Hawaii', no: 'Pizza Hawaii', nl: 'Pizza Hawaii', de: 'Pizza Hawaii'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pizzas', name: {tr: 'Pizza Bolognese', en: 'Pizza Bolognese', ru: 'Пицца Болоньезе', dk: 'Pizza Bolognese', fi: 'Pizza Bolognese', se: 'Pizza Bolognese', no: 'Pizza Bolognese', nl: 'Pizza Bolognese', de: 'Pizza Bolognese'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pizzas', name: {tr: 'Pizza Pepperoni', en: 'Pizza Pepperoni', ru: 'Пицца Пепперони', dk: 'Pizza Pepperoni', fi: 'Pizza Pepperoni', se: 'Pizza Pepperoni', no: 'Pizza Pepperoni', nl: 'Pizza Pepperoni', de: 'Pizza Pepperoni'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pizzas', name: {tr: 'Pizza Al Tonno', en: 'Pizza Al Tonno', ru: 'Пицца с тунцом', dk: 'Pizza Al Tonno', fi: 'Pizza Al Tonno', se: 'Pizza Al Tonno', no: 'Pizza Al Tonno', nl: 'Pizza Al Tonno', de: 'Pizza Al Tonno'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pizzas', name: {tr: 'Pizza Mexicano', en: 'Pizza Mexicano', ru: 'Пицца Мексикано', dk: 'Pizza Mexicano', fi: 'Pizza Mexicano', se: 'Pizza Mexicano', no: 'Pizza Mexicano', nl: 'Pizza Mexicano', de: 'Pizza Mexicano'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pizzas', name: {tr: 'Pizza Salami', en: 'Pizza Salami', ru: 'Пицца с салями', dk: 'Pizza Salami', fi: 'Pizza Salami', se: 'Pizza Salami', no: 'Pizza Salami', nl: 'Pizza Salami', de: 'Pizza Salami'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pizzas', name: {tr: 'Deniz Ürünleri Pizza', en: 'Pizza Sea Food', ru: 'Пицца с морепродуктами', dk: 'Pizza Hav Food', fi: 'Pizza Meri Food', se: 'Pizza Hav Food', no: 'Pizza Hav Food', nl: 'Pizza Zee Food', de: 'Pizza Meer Food'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pizzas', name: {tr: 'Karidesli Pizza', en: 'Pizza Shrimps', ru: 'Пицца с креветками', dk: 'Pizza Shrimps', fi: 'Pizza Shrimps', se: 'Pizza Shrimps', no: 'Pizza Shrimps', nl: 'Pizza Shrimps', de: 'Pizza Shrimps'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'pizzas', name: {tr: 'Tavuklu Pizza', en: 'Pizza Chicken', ru: 'Пицца с курицей', dk: 'Pizza Kylling', fi: 'Pizza Kana', se: 'Pizza Kyckling', no: 'Pizza Kylling', nl: 'Pizza Kip', de: 'Pizza Hähnchen'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },

    // SEA FOOD
    { category: 'seafood', name: {tr: 'Çipura', en: 'Sea Bream (Cupra)', ru: 'Дорада (Чупра)', dk: 'Hav Bream (Cupra)', fi: 'Meri Bream (Cupra)', se: 'Hav Bream (Cupra)', no: 'Hav Bream (Cupra)', nl: 'Zee Bream (Cupra)', de: 'Meer Bream (Cupra)'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'seafood', name: {tr: 'Sarımsaklı Karides', en: 'Garlic Shrimp', ru: 'Чесночные креветки', dk: 'Hvidløg Reje', fi: 'Valkosipuli Katkarapu', se: 'Vitlök Räka', no: 'Hvitløk Reke', nl: 'Knoflook Garnalen', de: 'Knoblauch Garnelen'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'seafood', name: {tr: 'Karides Güveç', en: 'Shrimp Casserole', ru: 'Креветки в горшочке', dk: 'Reje Casserole', fi: 'Katkarapu Casserole', se: 'Räka Casserole', no: 'Reke Casserole', nl: 'Garnalen Casserole', de: 'Garnelen Casserole'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'seafood', name: {tr: 'Kalamar Tava', en: 'Fried Calamari', ru: 'Жареные кальмары', dk: 'Stegt Calamari', fi: 'Paistettu Calamari', se: 'Friterad Calamari', no: 'Stekt Calamari', nl: 'Gebakken Calamari', de: 'Gebraten Calamari'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'seafood', name: {tr: 'Karışık Balık Tabağı', en: 'Mixed Fish Plate', ru: 'Ассорти из рыбы', dk: 'Blandet Fish Plate', fi: 'Sekoitettu Fish Plate', se: 'Blandad Fish Plate', no: 'Blandet Fish Plate', nl: 'Gemengd Fish Plate', de: 'Gemischt Fish Plate'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },

    // DESSERTS
    { category: 'desserts', name: {tr: 'Limonlu Cheesecake', en: 'Cheesecake Lemon', ru: 'Лимонный чизкейк', dk: 'Citroncheesecake', fi: 'Sitruunajuustokakku', se: 'Citroncheesecake', no: 'Sitroncheesecake', nl: 'Citroenkaasgebak', de: 'Zitronen-Käsekuchen'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'desserts', name: {tr: 'Dondurma', en: 'Ice Cream', ru: 'Мороженое', dk: 'Is', fi: 'Jäätelö', se: 'Glass', no: 'Is', nl: 'IJs', de: 'Eis'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'desserts', name: {tr: 'Tiramisu', en: 'Tiramisu', ru: 'Тирамису', dk: 'Tiramisu', fi: 'Tiramisu', se: 'Tiramisu', no: 'Tiramisu', nl: 'Tiramisu', de: 'Tiramisu'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'desserts', name: {tr: 'Pankek', en: 'Pancakes', ru: 'Блинчики', dk: 'Pandekager', fi: 'Pannukakut', se: 'Pannkakor', no: 'Pannekaker', nl: 'Pannenkoeken', de: 'Pfannkuchen'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },

    // FROZEN DRINKS
    { category: 'frozen-drinks', name: {tr: 'Frozen Strawberry Daiquiri', en: 'Frozen Strawberry Daiquiri', ru: 'Замороженный клубничный дайкири', dk: 'Frozen Jordbær Daiquiri', fi: 'Frozen Mansikka Daiquiri', se: 'Frozen Jordgubbe Daiquiri', no: 'Frozen Jordbær Daiquiri', nl: 'Frozen Aardbei Daiquiri', de: 'Frozen Erdbeere Daiquiri'}, desc: {tr: 'Bacardi, Fresh Lime, Sugar, Fresh Strawberries', en: 'Bacardi, Fresh Lime, Sugar, Fresh Strawberries', ru: 'Бакарди, свежий лайм, сахар, свежая клубника', dk: 'Bacardi, Frisk Lime, Sugar, Frisk Strawberries', fi: 'Bacardi, Tuore Lime, Sugar, Tuore Strawberries', se: 'Bacardi, Färsk Lime, Sugar, Färsk Strawberries', no: 'Bacardi, Fersk Lime, Sugar, Fersk Strawberries', nl: 'Bacardi, Vers Limoen, Sugar, Vers Strawberries', de: 'Bacardi, Frisch Limette, Sugar, Frisch Strawberries'}, price: '' },
    { category: 'frozen-drinks', name: {tr: 'Frozen Kiwi Daiquiri', en: 'Frozen Kiwi Daiquiri', ru: 'Замороженный киви дайкири', dk: 'Frozen Kiwi Daiquiri', fi: 'Frozen Kiwi Daiquiri', se: 'Frozen Kiwi Daiquiri', no: 'Frozen Kiwi Daiquiri', nl: 'Frozen Kiwi Daiquiri', de: 'Frozen Kiwi Daiquiri'}, desc: {tr: 'Bacardi, Fresh Lime, Sugar, Fresh Kiwi', en: 'Bacardi, Fresh Lime, Sugar, Fresh Kiwi', ru: 'Бакарди, свежий лайм, сахар, свежий киви', dk: 'Bacardi, Frisk Lime, Sugar, Frisk Kiwi', fi: 'Bacardi, Tuore Lime, Sugar, Tuore Kiwi', se: 'Bacardi, Färsk Lime, Sugar, Färsk Kiwi', no: 'Bacardi, Fersk Lime, Sugar, Fersk Kiwi', nl: 'Bacardi, Vers Limoen, Sugar, Vers Kiwi', de: 'Bacardi, Frisch Limette, Sugar, Frisch Kiwi'}, price: '' },
    { category: 'frozen-drinks', name: {tr: 'Frozen Peach Daiquiri', en: 'Frozen Peach Daiquiri', ru: 'Замороженный персиковый дайкири', dk: 'Frozen Peach Daiquiri', fi: 'Frozen Peach Daiquiri', se: 'Frozen Peach Daiquiri', no: 'Frozen Peach Daiquiri', nl: 'Frozen Peach Daiquiri', de: 'Frozen Peach Daiquiri'}, desc: {tr: 'Bacardi, Peach Juice, Sugar, Fresh Peach', en: 'Bacardi, Peach Juice, Sugar, Fresh Peach', ru: 'Бакарди, персиковый сок, сахар, свежий персик', dk: 'Bacardi, Peach Juice, Sugar, Frisk Peach', fi: 'Bacardi, Peach Mehu, Sugar, Tuore Peach', se: 'Bacardi, Peach Juice, Sugar, Färsk Peach', no: 'Bacardi, Peach Juice, Sugar, Fersk Peach', nl: 'Bacardi, Peach Sap, Sugar, Vers Peach', de: 'Bacardi, Peach Saft, Sugar, Frisch Peach'}, price: '' },
    { category: 'frozen-drinks', name: {tr: 'Frozen Mango Daiquiri', en: 'Frozen Mango Daiquiri', ru: 'Замороженный манго дайкири', dk: 'Frozen Mango Daiquiri', fi: 'Frozen Mango Daiquiri', se: 'Frozen Mango Daiquiri', no: 'Frozen Mango Daiquiri', nl: 'Frozen Mango Daiquiri', de: 'Frozen Mango Daiquiri'}, desc: {tr: 'Bacardi, Fresh Lime, Sugar, Fresh Mango', en: 'Bacardi, Fresh Lime, Sugar, Fresh Mango', ru: 'Бакарди, свежий лайм, сахар, свежее манго', dk: 'Bacardi, Frisk Lime, Sugar, Frisk Mango', fi: 'Bacardi, Tuore Lime, Sugar, Tuore Mango', se: 'Bacardi, Färsk Lime, Sugar, Färsk Mango', no: 'Bacardi, Fersk Lime, Sugar, Fersk Mango', nl: 'Bacardi, Vers Limoen, Sugar, Vers Mango', de: 'Bacardi, Frisch Limette, Sugar, Frisch Mango'}, price: '' },
    { category: 'frozen-drinks', name: {tr: 'Mojito', en: 'Mojito', ru: 'Мохито', dk: 'Mojito', fi: 'Mojito', se: 'Mojito', no: 'Mojito', nl: 'Mojito', de: 'Mojito'}, desc: {tr: 'Bacardi, Soda, Sugar, Lemon Juice, Fresh Mint Leaves, Crushed Ice', en: 'Bacardi, Soda, Sugar, Lemon Juice, Fresh Mint Leaves, Crushed Ice', ru: 'Бакарди, содовая, сахар, лимонный сок, свежая мята, колотый лед', dk: 'Bacardi, Soda, Sugar, Citron Juice, Frisk Mint Leaves, Crushed Is', fi: 'Bacardi, Soda, Sugar, Sitruuna Mehu, Tuore Mint Leaves, Crushed Jää', se: 'Bacardi, Soda, Sugar, Citron Juice, Färsk Mint Leaves, Crushed Is', no: 'Bacardi, Soda, Sugar, Sitron Juice, Fersk Mint Leaves, Crushed Is', nl: 'Bacardi, Soda, Sugar, Citroen Sap, Vers Mint Leaves, Crushed Ijs', de: 'Bacardi, Soda, Sugar, Zitrone Saft, Frisch Mint Leaves, Crushed Eis'}, price: '' },
    { category: 'frozen-drinks', name: {tr: 'Strawberry Mojito', en: 'Strawberry Mojito', ru: 'Клубничный мохито', dk: 'Jordbær Mojito', fi: 'Mansikka Mojito', se: 'Jordgubbe Mojito', no: 'Jordbær Mojito', nl: 'Aardbei Mojito', de: 'Erdbeere Mojito'}, desc: {tr: 'Bacardi, Soda, Lemon Juice, Fresh Strawberry, Fresh Mint Leaves, Crushed Ice, Strawberry Syrup', en: 'Bacardi, Soda, Lemon Juice, Fresh Strawberry, Fresh Mint Leaves, Crushed Ice, Strawberry Syrup', ru: 'Бакарди, содовая, лимонный сок, свежая клубника, свежая мята, колотый лед, клубничный сироп', dk: 'Bacardi, Soda, Citron Juice, Frisk Jordbær, Frisk Mint Leaves, Crushed Is, Jordbær Syrup', fi: 'Bacardi, Soda, Sitruuna Mehu, Tuore Mansikka, Tuore Mint Leaves, Crushed Jää, Mansikka Syrup', se: 'Bacardi, Soda, Citron Juice, Färsk Jordgubbe, Färsk Mint Leaves, Crushed Is, Jordgubbe Syrup', no: 'Bacardi, Soda, Sitron Juice, Fersk Jordbær, Fersk Mint Leaves, Crushed Is, Jordbær Syrup', nl: 'Bacardi, Soda, Citroen Sap, Vers Aardbei, Vers Mint Leaves, Crushed Ijs, Aardbei Syrup', de: 'Bacardi, Soda, Zitrone Saft, Frisch Erdbeere, Frisch Mint Leaves, Crushed Eis, Erdbeere Syrup'}, price: '' },
    { category: 'frozen-drinks', name: {tr: 'Caprinia', en: 'Caprinia', ru: 'Капириния', dk: 'Caprinia', fi: 'Caprinia', se: 'Caprinia', no: 'Caprinia', nl: 'Caprinia', de: 'Caprinia'}, desc: {tr: 'Rum, Lime, Brown Sugar, Crushed Ice', en: 'Rum, Lime, Brown Sugar, Crushed Ice', ru: 'Ром, лайм, коричневый сахар, колотый лед', dk: 'Rom, Lime, Brown Sugar, Crushed Is', fi: 'Rommi, Lime, Brown Sugar, Crushed Jää', se: 'Rom, Lime, Brown Sugar, Crushed Is', no: 'Rom, Lime, Brown Sugar, Crushed Is', nl: 'Rum, Limoen, Brown Sugar, Crushed Ijs', de: 'Rum, Limette, Brown Sugar, Crushed Eis'}, price: '' },
    { category: 'frozen-drinks', name: {tr: 'Aquarium Alanya', en: 'Aquarium Alanya', ru: 'Аквариум Аланья', dk: 'Aquarium Alanya', fi: 'Aquarium Alanya', se: 'Aquarium Alanya', no: 'Aquarium Alanya', nl: 'Aquarium Alanya', de: 'Aquarium Alanya'}, desc: {tr: '6 kişilik', en: '6 person', ru: 'На 6 человек', dk: '6 person', fi: '6 person', se: '6 person', no: '6 person', nl: '6 person', de: '6 person'}, price: '' },
    { category: 'frozen-drinks', name: {tr: 'Water Melon Dreams', en: 'Water Melon Dreams', ru: 'Арбузные мечты', dk: 'Water Melon Dreams', fi: 'Water Melon Dreams', se: 'Water Melon Dreams', no: 'Water Melon Dreams', nl: 'Water Melon Dreams', de: 'Water Melon Dreams'}, desc: {tr: '6 kişilik', en: '6 person', ru: 'На 6 человек', dk: '6 person', fi: '6 person', se: '6 person', no: '6 person', nl: '6 person', de: '6 person'}, price: '' },

    // SOFT DRINKS
    { category: 'soft-drinks', name: {tr: 'Kola', en: 'Cola', ru: 'Кола', dk: 'Cola', fi: 'Cola', se: 'Cola', no: 'Cola', nl: 'Cola', de: 'Cola'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'soft-drinks', name: {tr: 'Big Cola Light', en: 'Big Cola Light', ru: 'Биг Кола Лайт', dk: 'Big Cola Light', fi: 'Big Cola Light', se: 'Big Cola Light', no: 'Big Cola Light', nl: 'Big Cola Light', de: 'Big Cola Light'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'soft-drinks', name: {tr: 'Big Fanta', en: 'Big Fanta', ru: 'Биг Фанта', dk: 'Big Fanta', fi: 'Big Fanta', se: 'Big Fanta', no: 'Big Fanta', nl: 'Big Fanta', de: 'Big Fanta'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'soft-drinks', name: {tr: 'Big Sprite', en: 'Big Sprite', ru: 'Биг Спрайт', dk: 'Big Sprite', fi: 'Big Sprite', se: 'Big Sprite', no: 'Big Sprite', nl: 'Big Sprite', de: 'Big Sprite'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'soft-drinks', name: {tr: 'Coca-Cola', en: 'Coca-Cola', ru: 'Кока-Кола', dk: 'Coca-Cola', fi: 'Coca-Cola', se: 'Coca-Cola', no: 'Coca-Cola', nl: 'Coca-Cola', de: 'Coca-Cola'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'soft-drinks', name: {tr: 'Fanta Limon', en: 'Fanta Lemon', ru: 'Фанта Лимон', dk: 'Fanta Citron', fi: 'Fanta Sitruuna', se: 'Fanta Citron', no: 'Fanta Sitron', nl: 'Fanta Citroen', de: 'Fanta Zitrone'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'soft-drinks', name: {tr: 'Soğuk Çay', en: 'Ice Tea', ru: 'Холодный чай', dk: 'Is Tea', fi: 'Jää Tea', se: 'Is Tea', no: 'Is Tea', nl: 'Ijs Tea', de: 'Eis Tea'}, desc: {tr: 'Şeftali, Mango, Limon', en: 'Peach, Mango, Lemon', ru: 'Персик, манго, лимон', dk: 'Peach, Mango, Citron', fi: 'Peach, Mango, Sitruuna', se: 'Peach, Mango, Citron', no: 'Peach, Mango, Sitron', nl: 'Peach, Mango, Citroen', de: 'Peach, Mango, Zitrone'}, price: '' },
    { category: 'soft-drinks', name: {tr: 'Meyve Suyu', en: 'Fruit Juice', ru: 'Фруктовый сок', dk: 'Fruit Juice', fi: 'Fruit Mehu', se: 'Fruit Juice', no: 'Fruit Juice', nl: 'Fruit Sap', de: 'Fruit Saft'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'soft-drinks', name: {tr: 'Enerji İçeceği', en: 'Energy Drink', ru: 'Энергетический напиток', dk: 'Energy Drink', fi: 'Energy Drink', se: 'Energy Drink', no: 'Energy Drink', nl: 'Energy Drink', de: 'Energy Drink'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'soft-drinks', name: {tr: 'Soda', en: 'Soda', ru: 'Сода', dk: 'Soda', fi: 'Soda', se: 'Soda', no: 'Soda', nl: 'Soda', de: 'Soda'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'soft-drinks', name: {tr: 'Tonik', en: 'Tonic', ru: 'Тоник', dk: 'Tonic', fi: 'Tonic', se: 'Tonic', no: 'Tonic', nl: 'Tonic', de: 'Tonic'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'soft-drinks', name: {tr: 'Su 0.5 lt', en: 'Water 0.5 l', ru: 'Вода 0.5 л', dk: 'Water 0.5 l', fi: 'Water 0.5 l', se: 'Water 0.5 l', no: 'Water 0.5 l', nl: 'Water 0.5 l', de: 'Water 0.5 l'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'soft-drinks', name: {tr: 'Su 1.0 lt', en: 'Water 1.0 l', ru: 'Вода 1.0 л', dk: 'Water 1.0 l', fi: 'Water 1.0 l', se: 'Water 1.0 l', no: 'Water 1.0 l', nl: 'Water 1.0 l', de: 'Water 1.0 l'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'soft-drinks', name: {tr: 'Taze Portakal Suyu', en: 'Fresh Orange Juice', ru: 'Свежий апельсиновый сок', dk: 'Frisk Appelsin Juice', fi: 'Tuore Appelsiini Mehu', se: 'Färsk Apelsin Juice', no: 'Fersk Appelsin Juice', nl: 'Vers Sinaasappel Sap', de: 'Frisch Orange Saft'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },

    // BEER
    { category: 'beer', name: {tr: 'Efes Şişe (Big)', en: 'Efes Bottle (Big)', ru: 'Эфес Бутылка (Большая)', dk: 'Efes Bottle (Big)', fi: 'Efes Bottle (Big)', se: 'Efes Bottle (Big)', no: 'Efes Bottle (Big)', nl: 'Efes Bottle (Big)', de: 'Efes Bottle (Big)'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'beer', name: {tr: 'Efes Reserve', en: 'Efes Reserve', ru: 'Эфес Резерв', dk: 'Efes Reserve', fi: 'Efes Reserve', se: 'Efes Reserve', no: 'Efes Reserve', nl: 'Efes Reserve', de: 'Efes Reserve'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'beer', name: {tr: 'Tuborg Şişe (Big)', en: 'Tuborg Bottle (Big)', ru: 'Туборг Бутылка (Большая)', dk: 'Tuborg Bottle (Big)', fi: 'Tuborg Bottle (Big)', se: 'Tuborg Bottle (Big)', no: 'Tuborg Bottle (Big)', nl: 'Tuborg Bottle (Big)', de: 'Tuborg Bottle (Big)'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'beer', name: {tr: 'Bomonti', en: 'Bomonti', ru: 'Бомонти', dk: 'Bomonti', fi: 'Bomonti', se: 'Bomonti', no: 'Bomonti', nl: 'Bomonti', de: 'Bomonti'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'beer', name: {tr: 'Corona', en: 'Corona', ru: 'Корона', dk: 'Corona', fi: 'Corona', se: 'Corona', no: 'Corona', nl: 'Corona', de: 'Corona'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'beer', name: {tr: 'Carlsberg', en: 'Carlsberg', ru: 'Карлсберг', dk: 'Carlsberg', fi: 'Carlsberg', se: 'Carlsberg', no: 'Carlsberg', nl: 'Carlsberg', de: 'Carlsberg'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'beer', name: {tr: 'Miller', en: 'Miller', ru: 'Миллер', dk: 'Miller', fi: 'Miller', se: 'Miller', no: 'Miller', nl: 'Miller', de: 'Miller'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'beer', name: {tr: 'Guinness Dark', en: 'Guinness Dark', ru: 'Гиннесс Дарк', dk: 'Guinness Dark', fi: 'Guinness Dark', se: 'Guinness Dark', no: 'Guinness Dark', nl: 'Guinness Dark', de: 'Guinness Dark'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'beer', name: {tr: 'Cider', en: 'Cider', ru: 'Сидр', dk: 'Cider', fi: 'Cider', se: 'Cider', no: 'Cider', nl: 'Cider', de: 'Cider'}, desc: {tr: 'Apple, Strawberry', en: 'Apple, Strawberry', ru: 'Яблоко, клубника', dk: 'Apple, Jordbær', fi: 'Apple, Mansikka', se: 'Apple, Jordgubbe', no: 'Apple, Jordbær', nl: 'Apple, Aardbei', de: 'Apple, Erdbeere'}, price: '' },

    // WHISKEYS
    { category: 'whiskeys', name: {tr: 'Jack Daniel', en: 'Jack Daniel', ru: 'Джек Дэниелс', dk: 'Jack Daniel', fi: 'Jack Daniel', se: 'Jack Daniel', no: 'Jack Daniel', nl: 'Jack Daniel', de: 'Jack Daniel'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'whiskeys', name: {tr: 'Johny Walker', en: 'Johny Walker', ru: 'Джонни Уокер', dk: 'Johny Walker', fi: 'Johny Walker', se: 'Johny Walker', no: 'Johny Walker', nl: 'Johny Walker', de: 'Johny Walker'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'whiskeys', name: {tr: 'Jameson', en: 'Jameson', ru: 'Джеймсон', dk: 'Jameson', fi: 'Jameson', se: 'Jameson', no: 'Jameson', nl: 'Jameson', de: 'Jameson'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'whiskeys', name: {tr: 'JB', en: 'JB', ru: 'ДжБи', dk: 'JB', fi: 'JB', se: 'JB', no: 'JB', nl: 'JB', de: 'JB'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'whiskeys', name: {tr: 'Chivas', en: 'Chivas', ru: 'Чивас', dk: 'Chivas', fi: 'Chivas', se: 'Chivas', no: 'Chivas', nl: 'Chivas', de: 'Chivas'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'whiskeys', name: {tr: 'Yerli Viski', en: 'Local Whisky', ru: 'Локальный виски', dk: 'Local Whisky', fi: 'Local Viski', se: 'Local Whisky', no: 'Local Whisky', nl: 'Local Whisky', de: 'Local Whisky'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },

    // SHOTS
    { category: 'shots', name: {tr: 'B-52', en: 'B-52', ru: 'Б-52', dk: 'B-52', fi: 'B-52', se: 'B-52', no: 'B-52', nl: 'B-52', de: 'B-52'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'shots', name: {tr: 'Sambuca', en: 'Sambuca', ru: 'Самбука', dk: 'Sambuca', fi: 'Sambuca', se: 'Sambuca', no: 'Sambuca', nl: 'Sambuca', de: 'Sambuca'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'shots', name: {tr: 'Tequila', en: 'Tequila', ru: 'Текила', dk: 'Tequila', fi: 'Tequila', se: 'Tequila', no: 'Tequila', nl: 'Tequila', de: 'Tequila'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'shots', name: {tr: 'Jägermeister', en: 'Jägermeister', ru: 'Ягермейстер', dk: 'Jägermeister', fi: 'Jägermeister', se: 'Jägermeister', no: 'Jägermeister', nl: 'Jägermeister', de: 'Jägermeister'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'shots', name: {tr: 'Turkish Pepper', en: 'Turkish Pepper', ru: 'Турецкий перец', dk: 'Tyrkisk Peber', fi: 'Turkkilainen Pippuri', se: 'Turkisk Peppar', no: 'Tyrkisk Pepper', nl: 'Turks Peper', de: 'Türkisch Pfeffer'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'shots', name: {tr: 'Jeger Bom', en: 'Jeger Bom', ru: 'Йегер Бом', dk: 'Jeger Bom', fi: 'Jeger Bom', se: 'Jeger Bom', no: 'Jeger Bom', nl: 'Jeger Bom', de: 'Jeger Bom'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'shots', name: {tr: 'Sambuca Baileys', en: 'Sambuca Baileys', ru: 'Самбука Бейлис', dk: 'Sambuca Baileys', fi: 'Sambuca Baileys', se: 'Sambuca Baileys', no: 'Sambuca Baileys', nl: 'Sambuca Baileys', de: 'Sambuca Baileys'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'shots', name: {tr: 'Barmen Öpücüğü', en: 'Barmen Kiss', ru: 'Поцелуй бармена', dk: 'Barmen Kiss', fi: 'Barmen Kiss', se: 'Barmen Kiss', no: 'Barmen Kiss', nl: 'Barmen Kiss', de: 'Barmen Kiss'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },

    // WATER PIPE
    // { category: 'water-pipe', name: {tr: 'LOVE 66', en: 'LOVE 66', ru: 'ЛОВЕ 66', dk: 'LOVE 66', fi: 'LOVE 66', se: 'LOVE 66', no: 'LOVE 66', nl: 'LOVE 66', de: 'LOVE 66'}, desc: {tr: 'WATERMELON, STRAWBERRY, MINT, GUM', en: 'WATERMELON, STRAWBERRY, MINT, GUM', ru: 'АРБУЗ, КЛУБНИКА, МЯТА, ЖВАЧКА', dk: 'WATERMELON, Jordbær, MINT, GUM', fi: 'WATERMELON, Mansikka, MINT, GUM', se: 'WATERMELON, Jordgubbe, MINT, GUM', no: 'WATERMELON, Jordbær, MINT, GUM', nl: 'WATERMELON, Aardbei, MINT, GUM', de: 'WATERMELON, Erdbeere, MINT, GUM'}, price: '' },
    // { category: 'water-pipe', name: {tr: 'LADY KİLLER', en: 'LADY KILLER', ru: 'КИЛЛЕР ЛЕДИ', dk: 'LADY KILLER', fi: 'LADY KILLER', se: 'LADY KILLER', no: 'LADY KILLER', nl: 'LADY KILLER', de: 'LADY KILLER'}, desc: {tr: 'MANGO, HONEYMELON, STRAWBERRY', en: 'MANGO, HONEYMELON, STRAWBERRY', ru: 'МАНГО, МЕДОВАЯ ДЫНЯ, КЛУБНИКА', dk: 'MANGO, HONEYMELON, Jordbær', fi: 'MANGO, HONEYMELON, Mansikka', se: 'MANGO, HONEYMELON, Jordgubbe', no: 'MANGO, HONEYMELON, Jordbær', nl: 'MANGO, HONEYMELON, Aardbei', de: 'MANGO, HONEYMELON, Erdbeere'}, price: '' },
    // { category: 'water-pipe', name: {tr: 'ICE BONBON', en: 'ICE BONBON', ru: 'ЛЕДЯНОЕ КОНФЕТА', dk: 'Is BONBON', fi: 'Jää BONBON', se: 'Is BONBON', no: 'Is BONBON', nl: 'Ijs BONBON', de: 'Eis BONBON'}, desc: {tr: 'MANGO, HONEYMELON, STRAWBERRY', en: 'MANGO, HONEYMELON, STRAWBERRY', ru: 'МАНГО, МЕДОВАЯ ДЫНЯ, КЛУБНИКА', dk: 'MANGO, HONEYMELON, Jordbær', fi: 'MANGO, HONEYMELON, Mansikka', se: 'MANGO, HONEYMELON, Jordgubbe', no: 'MANGO, HONEYMELON, Jordbær', nl: 'MANGO, HONEYMELON, Aardbei', de: 'MANGO, HONEYMELON, Erdbeere'}, price: '' },
    // { category: 'water-pipe', name: {tr: 'DEJAVU', en: 'DEJAVU', ru: 'ДЕЖАВЮ', dk: 'DEJAVU', fi: 'DEJAVU', se: 'DEJAVU', no: 'DEJAVU', nl: 'DEJAVU', de: 'DEJAVU'}, desc: {tr: 'WATERMELON, MELON, VANILLA', en: 'WATERMELON, MELON, VANILLA', ru: 'АРБУЗ, ДЫНЯ, ВАНИЛЬ', dk: 'WATERMELON, MELON, Vanilje', fi: 'WATERMELON, MELON, Vanilja', se: 'WATERMELON, MELON, Vanilj', no: 'WATERMELON, MELON, Vanilje', nl: 'WATERMELON, MELON, Vanille', de: 'WATERMELON, MELON, Vanille'}, price: '' },
    // { category: 'water-pipe', name: {tr: 'ZEUS', en: 'ZEUS', ru: 'ЗЕВС', dk: 'ZEUS', fi: 'ZEUS', se: 'ZEUS', no: 'ZEUS', nl: 'ZEUS', de: 'ZEUS'}, desc: {tr: 'WATERMELON, PEACH MARACUJA', en: 'WATERMELON, PEACH MARACUJA', ru: 'АРБУЗ, ПЕРСИК МАРАКУЙЯ', dk: 'WATERMELON, PEACH MARACUJA', fi: 'WATERMELON, PEACH MARACUJA', se: 'WATERMELON, PEACH MARACUJA', no: 'WATERMELON, PEACH MARACUJA', nl: 'WATERMELON, PEACH MARACUJA', de: 'WATERMELON, PEACH MARACUJA'}, price: '' },
    // { category: 'water-pipe', name: {tr: 'BAKU NIGHT', en: 'BAKU NIGHT', ru: 'НОЧЬ В БАКУ', dk: 'BAKU NIGHT', fi: 'BAKU NIGHT', se: 'BAKU NIGHT', no: 'BAKU NIGHT', nl: 'BAKU NIGHT', de: 'BAKU NIGHT'}, desc: {tr: 'Forest fruit, sweet mint', en: 'Forest fruit, sweet mint', ru: 'Лесные ягоды, сладкая мята', dk: 'Forest fruit, sweet mint', fi: 'Forest fruit, sweet mint', se: 'Forest fruit, sweet mint', no: 'Forest fruit, sweet mint', nl: 'Forest fruit, sweet mint', de: 'Forest fruit, sweet mint'}, price: '' },
    // { category: 'water-pipe', name: {tr: 'DOUBLE APPLE', en: 'DOUBLE APPLE', ru: 'ДВОЙНОЕ ЯБЛОКО', dk: 'DOUBLE APPLE', fi: 'DOUBLE APPLE', se: 'DOUBLE APPLE', no: 'DOUBLE APPLE', nl: 'DOUBLE APPLE', de: 'DOUBLE APPLE'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    // { category: 'water-pipe', name: {tr: 'MINT', en: 'MINT', ru: 'МЯТА', dk: 'MINT', fi: 'MINT', se: 'MINT', no: 'MINT', nl: 'MINT', de: 'MINT'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },

    // MILKSHAKES
    { category: 'milkshakes', name: {tr: 'Muzlu Milkshake', en: 'Banana Milkshake', ru: 'Банановый милкшейк', dk: 'Banan Milkshake', fi: 'Banaani Milkshake', se: 'Banan Milkshake', no: 'Banan Milkshake', nl: 'Banaan Milkshake', de: 'Banane Milkshake'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'milkshakes', name: {tr: 'Çilekli Milkshake', en: 'Strawberry Milkshake', ru: 'Клубничный милкшейк', dk: 'Jordbær Milkshake', fi: 'Mansikka Milkshake', se: 'Jordgubbe Milkshake', no: 'Jordbær Milkshake', nl: 'Aardbei Milkshake', de: 'Erdbeere Milkshake'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'milkshakes', name: {tr: 'Vanilya Milkshake', en: 'Vanilla Milkshake', ru: 'Ванильный милкшейк', dk: 'Vanilje Milkshake', fi: 'Vanilja Milkshake', se: 'Vanilj Milkshake', no: 'Vanilje Milkshake', nl: 'Vanille Milkshake', de: 'Vanille Milkshake'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'milkshakes', name: {tr: 'Kakao Milkshake', en: 'Cocoa Milkshake', ru: 'Какао милкшейк', dk: 'Kakao Milkshake', fi: 'Kaakao Milkshake', se: 'Kakao Milkshake', no: 'Kakao Milkshake', nl: 'Cacao Milkshake', de: 'Kakao Milkshake'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },
    { category: 'milkshakes', name: {tr: 'Buzlu Kahve', en: 'Ice Coffee', ru: 'Айс-кофе', dk: 'Is Kaffe', fi: 'Jää Kahvi', se: 'Is Kaffe', no: 'Is Kaffe', nl: 'Ijs Koffie', de: 'Eis Kaffee'}, desc: {tr: '', en: '', ru: '', dk: '', fi: '', se: '', no: '', nl: '', de: ''}, price: '' },

    // COCKTAILS
    { category: 'cocktails', name: {tr: 'Long Island Ice Tea', en: 'Long Island Ice Tea', ru: 'Лонг Айленд', dk: 'Long Island Is Tea', fi: 'Long Island Jää Tea', se: 'Long Island Is Tea', no: 'Long Island Is Tea', nl: 'Long Island Ijs Tea', de: 'Long Island Eis Tea'}, desc: {tr: 'Bacardi, Vodka, Gin, Tequila, Cointreau, Lemon Juice, Ice', en: 'Bacardi, Vodka, Gin, Tequila, Cointreau, Lemon Juice, Ice', ru: 'Бакарди, водка, джин, текила, куантро, лимонный сок, лед', dk: 'Bacardi, Vodka, Gin, Tequila, Cointreau, Citron Juice, Is', fi: 'Bacardi, Vodka, Gin, Tequila, Cointreau, Sitruuna Mehu, Jää', se: 'Bacardi, Vodka, Gin, Tequila, Cointreau, Citron Juice, Is', no: 'Bacardi, Vodka, Gin, Tequila, Cointreau, Sitron Juice, Is', nl: 'Bacardi, Vodka, Gin, Tequila, Cointreau, Citroen Sap, Ijs', de: 'Bacardi, Wodka, Gin, Tequila, Cointreau, Zitrone Saft, Eis'}, price: '' },
    { category: 'cocktails', name: {tr: 'Barman Special', en: 'Barman Special', ru: 'Спецзаказ барменом', dk: 'Barman Special', fi: 'Barman Erityinen', se: 'Barman Special', no: 'Barman Spesial', nl: 'Barman Special', de: 'Barman Special'}, desc: {tr: 'Bacardi, Cointreau, Orange Juice, Blue Curacao', en: 'Bacardi, Cointreau, Orange Juice, Blue Curacao', ru: 'Бакарди, куантро, апельсиновый сок, голубой кюрасао', dk: 'Bacardi, Cointreau, Appelsin Juice, Blå Curacao', fi: 'Bacardi, Cointreau, Appelsiini Mehu, Sininen Curacao', se: 'Bacardi, Cointreau, Apelsin Juice, Blå Curacao', no: 'Bacardi, Cointreau, Appelsin Juice, Blå Curacao', nl: 'Bacardi, Cointreau, Sinaasappel Sap, Blauw Curacao', de: 'Bacardi, Cointreau, Orange Saft, Blau Curacao'}, price: '' },
    { category: 'cocktails', name: {tr: 'Acapulco', en: 'Acapulco', ru: 'Акапулько', dk: 'Acapulco', fi: 'Acapulco', se: 'Acapulco', no: 'Acapulco', nl: 'Acapulco', de: 'Acapulco'}, desc: {tr: 'Tequila, Bacardi, Pineapple Juice, Cream de Coconut', en: 'Tequila, Bacardi, Pineapple Juice, Cream de Coconut', ru: 'Текила, бакарди, ананасовый сок, кокосовый крем', dk: 'Tequila, Bacardi, Ananas Juice, Fløde de Coconut', fi: 'Tequila, Bacardi, Ananas Mehu, Kerma de Coconut', se: 'Tequila, Bacardi, Ananas Juice, Grädde de Coconut', no: 'Tequila, Bacardi, Ananas Juice, Fløte de Coconut', nl: 'Tequila, Bacardi, Ananas Sap, Room de Coconut', de: 'Tequila, Bacardi, Ananas Saft, Sahne de Coconut'}, price: '' },
    { category: 'cocktails', name: {tr: 'Blue Hawaii', en: 'Blue Hawaii', ru: 'Голубые Гавайи', dk: 'Blå Hawaii', fi: 'Sininen Hawaii', se: 'Blå Hawaii', no: 'Blå Hawaii', nl: 'Blauw Hawaii', de: 'Blau Hawaii'}, desc: {tr: 'Bacardi, Blue Curacao, Malibu, Pineapple Juice', en: 'Bacardi, Blue Curacao, Malibu, Pineapple Juice', ru: 'Бакарди, голубой кюрасао, малибу, ананасовый сок', dk: 'Bacardi, Blå Curacao, Malibu, Ananas Juice', fi: 'Bacardi, Sininen Curacao, Malibu, Ananas Mehu', se: 'Bacardi, Blå Curacao, Malibu, Ananas Juice', no: 'Bacardi, Blå Curacao, Malibu, Ananas Juice', nl: 'Bacardi, Blauw Curacao, Malibu, Ananas Sap', de: 'Bacardi, Blau Curacao, Malibu, Ananas Saft'}, price: '' },
    { category: 'cocktails', name: {tr: 'Pina Colada', en: 'Pina Colada', ru: 'Пина Колада', dk: 'Pina Colada', fi: 'Pina Colada', se: 'Pina Colada', no: 'Pina Colada', nl: 'Pina Colada', de: 'Pina Colada'}, desc: {tr: 'Bacardi, Malibu, Milk, Pineapple Juice', en: 'Bacardi, Malibu, Milk, Pineapple Juice', ru: 'Бакарди, малибу, молоко, ананасовый сок', dk: 'Bacardi, Malibu, Milk, Ananas Juice', fi: 'Bacardi, Malibu, Milk, Ananas Mehu', se: 'Bacardi, Malibu, Milk, Ananas Juice', no: 'Bacardi, Malibu, Milk, Ananas Juice', nl: 'Bacardi, Malibu, Milk, Ananas Sap', de: 'Bacardi, Malibu, Milk, Ananas Saft'}, price: '' },
    { category: 'cocktails', name: {tr: 'Tequila Sunrise', en: 'Tequila Sunrise', ru: 'Восход над Текилой', dk: 'Tequila Sunrise', fi: 'Tequila Sunrise', se: 'Tequila Sunrise', no: 'Tequila Sunrise', nl: 'Tequila Sunrise', de: 'Tequila Sunrise'}, desc: {tr: 'Tequila, Cointreau, Orange Juice, Grenadine', en: 'Tequila, Cointreau, Orange Juice, Grenadine', ru: 'Текила, куантро, апельсиновый сок, гренадин', dk: 'Tequila, Cointreau, Appelsin Juice, Grenadine', fi: 'Tequila, Cointreau, Appelsiini Mehu, Grenadine', se: 'Tequila, Cointreau, Apelsin Juice, Grenadine', no: 'Tequila, Cointreau, Appelsin Juice, Grenadine', nl: 'Tequila, Cointreau, Sinaasappel Sap, Grenadine', de: 'Tequila, Cointreau, Orange Saft, Grenadine'}, price: '' },
    { category: 'cocktails', name: {tr: 'Malibu Sunset', en: 'Malibu Sunset', ru: 'Закат Малибу', dk: 'Malibu Sunset', fi: 'Malibu Sunset', se: 'Malibu Sunset', no: 'Malibu Sunset', nl: 'Malibu Sunset', de: 'Malibu Sunset'}, desc: {tr: 'Vodka, Malibu, Pineapple Juice, Grenadine', en: 'Vodka, Malibu, Pineapple Juice, Grenadine', ru: 'Водка, малибу, ананасовый сок, гренадин', dk: 'Vodka, Malibu, Ananas Juice, Grenadine', fi: 'Vodka, Malibu, Ananas Mehu, Grenadine', se: 'Vodka, Malibu, Ananas Juice, Grenadine', no: 'Vodka, Malibu, Ananas Juice, Grenadine', nl: 'Vodka, Malibu, Ananas Sap, Grenadine', de: 'Wodka, Malibu, Ananas Saft, Grenadine'}, price: '' },
    { category: 'cocktails', name: {tr: 'Blue Lagoon', en: 'Blue Lagoon', ru: 'Голубая лагуна', dk: 'Blå Lagoon', fi: 'Sininen Lagoon', se: 'Blå Lagoon', no: 'Blå Lagoon', nl: 'Blauw Lagoon', de: 'Blau Lagoon'}, desc: {tr: 'Vodka, Sprite, Lemon, Blue Curacao', en: 'Vodka, Sprite, Lemon, Blue Curacao', ru: 'Водка, спрайт, лимон, голубой кюрасао', dk: 'Vodka, Sprite, Citron, Blå Curacao', fi: 'Vodka, Sprite, Sitruuna, Sininen Curacao', se: 'Vodka, Sprite, Citron, Blå Curacao', no: 'Vodka, Sprite, Sitron, Blå Curacao', nl: 'Vodka, Sprite, Citroen, Blauw Curacao', de: 'Wodka, Sprite, Zitrone, Blau Curacao'}, price: '' },
    { category: 'cocktails', name: {tr: 'Black Russian', en: 'Black Russian', ru: 'Черный русский', dk: 'Black Russian', fi: 'Black Russian', se: 'Black Russian', no: 'Black Russian', nl: 'Black Russian', de: 'Black Russian'}, desc: {tr: 'Kahlua, Vodka, Coffee Liqueur, Ice', en: 'Kahlua, Vodka, Coffee Liqueur, Ice', ru: 'Калуа, водка, кофейный ликер, лед', dk: 'Kahlua, Vodka, Kaffe Liqueur, Is', fi: 'Kahlua, Vodka, Kahvi Liqueur, Jää', se: 'Kahlua, Vodka, Kaffe Liqueur, Is', no: 'Kahlua, Vodka, Kaffe Liqueur, Is', nl: 'Kahlua, Vodka, Koffie Liqueur, Ijs', de: 'Kahlua, Wodka, Kaffee Liqueur, Eis'}, price: '' },
    { category: 'cocktails', name: {tr: 'White Russian', en: 'White Russian', ru: 'Белый русский', dk: 'White Russian', fi: 'White Russian', se: 'White Russian', no: 'White Russian', nl: 'White Russian', de: 'White Russian'}, desc: {tr: 'Kahlua, Vodka, Cream, Ice', en: 'Kahlua, Vodka, Cream, Ice', ru: 'Калуа, водка, сливки, лед', dk: 'Kahlua, Vodka, Fløde, Is', fi: 'Kahlua, Vodka, Kerma, Jää', se: 'Kahlua, Vodka, Grädde, Is', no: 'Kahlua, Vodka, Fløte, Is', nl: 'Kahlua, Vodka, Room, Ijs', de: 'Kahlua, Wodka, Sahne, Eis'}, price: '' },
    { category: 'cocktails', name: {tr: 'Cuba Libre', en: 'Cuba Libre', ru: 'Куба Либре', dk: 'Cuba Libre', fi: 'Cuba Libre', se: 'Cuba Libre', no: 'Cuba Libre', nl: 'Cuba Libre', de: 'Cuba Libre'}, desc: {tr: 'Bacardi, Cola, Lime', en: 'Bacardi, Cola, Lime', ru: 'Бакарди, кола, лайм', dk: 'Bacardi, Cola, Lime', fi: 'Bacardi, Cola, Lime', se: 'Bacardi, Cola, Lime', no: 'Bacardi, Cola, Lime', nl: 'Bacardi, Cola, Limoen', de: 'Bacardi, Cola, Limette'}, price: '' },
    { category: 'cocktails', name: {tr: 'Cosmopolitan', en: 'Cosmopolitan', ru: 'Космополитен', dk: 'Cosmopolitan', fi: 'Cosmopolitan', se: 'Cosmopolitan', no: 'Cosmopolitan', nl: 'Cosmopolitan', de: 'Cosmopolitan'}, desc: {tr: 'Bacardi, Lemon Juice, Sprite, Grenadine', en: 'Bacardi, Lemon Juice, Sprite, Grenadine', ru: 'Бакарди, лимонный сок, спрайт, гренадин', dk: 'Bacardi, Citron Juice, Sprite, Grenadine', fi: 'Bacardi, Sitruuna Mehu, Sprite, Grenadine', se: 'Bacardi, Citron Juice, Sprite, Grenadine', no: 'Bacardi, Sitron Juice, Sprite, Grenadine', nl: 'Bacardi, Citroen Sap, Sprite, Grenadine', de: 'Bacardi, Zitrone Saft, Sprite, Grenadine'}, price: '' },
    { category: 'cocktails', name: {tr: 'San Francisco', en: 'San Francisco', ru: 'Сан-Франциско', dk: 'San Francisco', fi: 'San Francisco', se: 'San Francisco', no: 'San Francisco', nl: 'San Francisco', de: 'San Francisco'}, desc: {tr: 'Vodka, Banana Liqueur, Orange Juice, Grenadine', en: 'Vodka, Banana Liqueur, Orange Juice, Grenadine', ru: 'Водка, банановый ликер, апельсиновый сок, гренадин', dk: 'Vodka, Banan Liqueur, Appelsin Juice, Grenadine', fi: 'Vodka, Banaani Liqueur, Appelsiini Mehu, Grenadine', se: 'Vodka, Banan Liqueur, Apelsin Juice, Grenadine', no: 'Vodka, Banan Liqueur, Appelsin Juice, Grenadine', nl: 'Vodka, Banaan Liqueur, Sinaasappel Sap, Grenadine', de: 'Wodka, Banane Liqueur, Orange Saft, Grenadine'}, price: '' },
    { category: 'cocktails', name: {tr: 'Bloody Mary', en: 'Bloody Mary', ru: 'Кровавая Мэри', dk: 'Bloody Mary', fi: 'Bloody Mary', se: 'Bloody Mary', no: 'Bloody Mary', nl: 'Bloody Mary', de: 'Bloody Mary'}, desc: {tr: 'Vodka, Cointreau, Lime, Tomato Juice, Salt, Paprika Hot Sauce', en: 'Vodka, Cointreau, Lime, Tomato Juice, Salt, Paprika Hot Sauce', ru: 'Водка, куантро, лайм, томатный сок, соль, острый паприка', dk: 'Vodka, Cointreau, Lime, Tomat Juice, Salt, Paprika Hot Sauce', fi: 'Vodka, Cointreau, Lime, Tomaatti Mehu, Suola, Paprika Hot Sauce', se: 'Vodka, Cointreau, Lime, Tomat Juice, Salt, Paprika Hot Sauce', no: 'Vodka, Cointreau, Lime, Tomat Juice, Salt, Paprika Hot Sauce', nl: 'Vodka, Cointreau, Limoen, Tomaat Sap, Zout, Paprika Hot Sauce', de: 'Wodka, Cointreau, Limette, Tomate Saft, Salz, Paprika Hot Sauce'}, price: '' },
    { category: 'cocktails', name: {tr: 'Tom Collins', en: 'Tom Collins', ru: 'Том Коллинз', dk: 'Tom Collins', fi: 'Tom Collins', se: 'Tom Collins', no: 'Tom Collins', nl: 'Tom Collins', de: 'Tom Collins'}, desc: {tr: 'Gin, Lemon Juice, Sugar Syrup, Mineral Water', en: 'Gin, Lemon Juice, Sugar Syrup, Mineral Water', ru: 'Джин, лимонный сок, сахарный сироп, минеральная вода', dk: 'Gin, Citron Juice, Sugar Syrup, Mineral Water', fi: 'Gin, Sitruuna Mehu, Sugar Syrup, Mineral Water', se: 'Gin, Citron Juice, Sugar Syrup, Mineral Water', no: 'Gin, Sitron Juice, Sugar Syrup, Mineral Water', nl: 'Gin, Citroen Sap, Sugar Syrup, Mineral Water', de: 'Gin, Zitrone Saft, Sugar Syrup, Mineral Water'}, price: '' },
    { category: 'cocktails', name: {tr: 'Casablanca', en: 'Casablanca', ru: 'Касабланка', dk: 'Casablanca', fi: 'Casablanca', se: 'Casablanca', no: 'Casablanca', nl: 'Casablanca', de: 'Casablanca'}, desc: {tr: 'Rum, Malibu, Pineapple Juice, Grenadine', en: 'Rum, Malibu, Pineapple Juice, Grenadine', ru: 'Ром, малибу, ананасовый сок, гренадин', dk: 'Rom, Malibu, Ananas Juice, Grenadine', fi: 'Rommi, Malibu, Ananas Mehu, Grenadine', se: 'Rom, Malibu, Ananas Juice, Grenadine', no: 'Rom, Malibu, Ananas Juice, Grenadine', nl: 'Rum, Malibu, Ananas Sap, Grenadine', de: 'Rum, Malibu, Ananas Saft, Grenadine'}, price: '' },
    { category: 'cocktails', name: {tr: 'Harley Davidson', en: 'Harley Davidson', ru: 'Харлей-Дэвидсон', dk: 'Harley Davidson', fi: 'Harley Davidson', se: 'Harley Davidson', no: 'Harley Davidson', nl: 'Harley Davidson', de: 'Harley Davidson'}, desc: {tr: 'Baileys, Malibu, Whisky, Crushed Ice', en: 'Baileys, Malibu, Whisky, Crushed Ice', ru: 'Бейлис, малибу, виски, колотый лед', dk: 'Baileys, Malibu, Whisky, Crushed Is', fi: 'Baileys, Malibu, Viski, Crushed Jää', se: 'Baileys, Malibu, Whisky, Crushed Is', no: 'Baileys, Malibu, Whisky, Crushed Is', nl: 'Baileys, Malibu, Whisky, Crushed Ijs', de: 'Baileys, Malibu, Whisky, Crushed Eis'}, price: '' },
    { category: 'cocktails', name: {tr: 'African Inn', en: 'African Inn', ru: 'Африканская гостиница', dk: 'African Inn', fi: 'African Inn', se: 'African Inn', no: 'African Inn', nl: 'African Inn', de: 'African Inn'}, desc: {tr: 'Safari, Pineapple Juice, Orange Juice', en: 'Safari, Pineapple Juice, Orange Juice', ru: 'Сафари, ананасовый сок, апельсиновый сок', dk: 'Safari, Ananas Juice, Appelsin Juice', fi: 'Safari, Ananas Mehu, Appelsiini Mehu', se: 'Safari, Ananas Juice, Apelsin Juice', no: 'Safari, Ananas Juice, Appelsin Juice', nl: 'Safari, Ananas Sap, Sinaasappel Sap', de: 'Safari, Ananas Saft, Orange Saft'}, price: '' },
    { category: 'cocktails', name: {tr: 'Ecstasy', en: 'Ecstasy', ru: 'Экстаз', dk: 'Ecstasy', fi: 'Ecstasy', se: 'Ecstasy', no: 'Ecstasy', nl: 'Ecstasy', de: 'Ecstasy'}, desc: {tr: 'Bacardi, Tequila, Safari, Cointreau, Red Bull', en: 'Bacardi, Tequila, Safari, Cointreau, Red Bull', ru: 'Бакарди, текила, сафари, куантро, энергетик', dk: 'Bacardi, Tequila, Safari, Cointreau, Red Bull', fi: 'Bacardi, Tequila, Safari, Cointreau, Red Bull', se: 'Bacardi, Tequila, Safari, Cointreau, Red Bull', no: 'Bacardi, Tequila, Safari, Cointreau, Red Bull', nl: 'Bacardi, Tequila, Safari, Cointreau, Red Bull', de: 'Bacardi, Tequila, Safari, Cointreau, Red Bull'}, price: '' },
    { category: 'cocktails', name: {tr: 'Poison', en: 'Poison', ru: 'Яд', dk: 'Poison', fi: 'Poison', se: 'Poison', no: 'Poison', nl: 'Poison', de: 'Poison'}, desc: {tr: 'Gin, Cointreau, Archers, Pineapple Juice', en: 'Gin, Cointreau, Archers, Pineapple Juice', ru: 'Джин, куантро, лучники, ананасовый сок', dk: 'Gin, Cointreau, Archers, Ananas Juice', fi: 'Gin, Cointreau, Archers, Ananas Mehu', se: 'Gin, Cointreau, Archers, Ananas Juice', no: 'Gin, Cointreau, Archers, Ananas Juice', nl: 'Gin, Cointreau, Archers, Ananas Sap', de: 'Gin, Cointreau, Archers, Ananas Saft'}, price: '' },
    { category: 'cocktails', name: {tr: 'Salim Special', en: 'Salim Special', ru: 'Салим Специал', dk: 'Salim Special', fi: 'Salim Erityinen', se: 'Salim Special', no: 'Salim Spesial', nl: 'Salim Special', de: 'Salim Special'}, desc: {tr: 'SECRET', en: 'SECRET', ru: 'СЕКРЕТ', dk: 'Hemmelig', fi: 'Salainen', se: 'Hemlig', no: 'Hemmelig', nl: 'Geheim', de: 'Geheim'}, price: '' },


    // sexy cocktails

    {category:'sexycocktails',name:{tr: 'Hot Love', en: 'Hot Love', ru: 'Горячая любовь', dk: 'Hot Love', fi: 'Hot Love', se: 'Hot Love', no: 'Hot Love', nl: 'Hot Love', de: 'Hot Love'},desc:{tr: 'Rom, votka, tekila, portakal suyu, grenadin', en: 'Rum, vodka, tequila, orange juice, grenadine', ru: 'Ром, водка, текила, апельсиновый сок, гренадин', dk: 'Rom, vodka, tequila, appelsin juice, grenadine', fi: 'Rommi, vodka, tequila, appelsiini mehu, grenadine', se: 'Rom, vodka, tequila, apelsin juice, grenadine', no: 'Rom, vodka, tequila, appelsin juice, grenadine', nl: 'Rum, vodka, tequila, sinaasappel sap, grenadine', de: 'Rum, Wodka, Tequila, Orange Saft, grenadine'},price:''},
{category:'sexycocktails',name:{tr: 'Sex on the Beach', en: 'Sex on the Beach', ru: 'Секс на пляже', dk: 'Sex on the Beach', fi: 'Sex on the Beach', se: 'Sex on the Beach', no: 'Sex on the Beach', nl: 'Sex on the Beach', de: 'Sex on the Beach'},desc:{tr: 'Votka, tekila, Archers, portakal suyu, grenadin', en: 'Vodka, tequila, Archers, orange juice, grenadine', ru: 'Водка, текила, Archers, апельсиновый сок, гренадин', dk: 'Vodka, tequila, Archers, appelsin juice, grenadine', fi: 'Vodka, tequila, Archers, appelsiini mehu, grenadine', se: 'Vodka, tequila, Archers, apelsin juice, grenadine', no: 'Vodka, tequila, Archers, appelsin juice, grenadine', nl: 'Vodka, tequila, Archers, sinaasappel sap, grenadine', de: 'Wodka, Tequila, Archers, Orange Saft, grenadine'},price:''},
{category:'sexycocktails',name:{tr: 'Orgasm', en: 'Orgasm', ru: 'Оргазм', dk: 'Orgasm', fi: 'Orgasm', se: 'Orgasm', no: 'Orgasm', nl: 'Orgasm', de: 'Orgasm'},desc:{tr: 'Votka, Baileys, Amaretto, süt, krema', en: 'Vodka, Baileys, Amaretto, milk, cream', ru: 'Водка, Baileys, амаретто, молоко, сливки', dk: 'Vodka, Baileys, Amaretto, milk, fløde', fi: 'Vodka, Baileys, Amaretto, milk, kerma', se: 'Vodka, Baileys, Amaretto, milk, grädde', no: 'Vodka, Baileys, Amaretto, milk, fløte', nl: 'Vodka, Baileys, Amaretto, milk, room', de: 'Wodka, Baileys, Amaretto, milk, Sahne'},price:''},
{category:'sexycocktails',name:{tr: 'Viagra', en: 'Viagra', ru: 'Виагра', dk: 'Viagra', fi: 'Viagra', se: 'Viagra', no: 'Viagra', nl: 'Viagra', de: 'Viagra'},desc:{tr: 'Votka, Cointreau, Red Bull, Blue Curaçao', en: 'Vodka, Cointreau, Red Bull, Blue Curaçao', ru: 'Водка, Cointreau, Red Bull, Blue Curaçao', dk: 'Vodka, Cointreau, Red Bull, Blå Curaçao', fi: 'Vodka, Cointreau, Red Bull, Sininen Curaçao', se: 'Vodka, Cointreau, Red Bull, Blå Curaçao', no: 'Vodka, Cointreau, Red Bull, Blå Curaçao', nl: 'Vodka, Cointreau, Red Bull, Blauw Curaçao', de: 'Wodka, Cointreau, Red Bull, Blau Curaçao'},price:''},
{category:'sexycocktails',name:{tr: 'Sea Sun Sex', en: 'Sea Sun Sex', ru: 'Море Солнце Секс', dk: 'Hav Sun Sex', fi: 'Meri Sun Sex', se: 'Hav Sun Sex', no: 'Hav Sun Sex', nl: 'Zee Sun Sex', de: 'Meer Sun Sex'},desc:{tr: 'Votka, Archers, Kahlua, ananas suyu, grenadin', en: 'Vodka, Archers, Kahlua, pineapple juice, grenadine', ru: 'Водка, Archers, Kahlua, ананасовый сок, гренадин', dk: 'Vodka, Archers, Kahlua, ananas juice, grenadine', fi: 'Vodka, Archers, Kahlua, ananas mehu, grenadine', se: 'Vodka, Archers, Kahlua, ananas juice, grenadine', no: 'Vodka, Archers, Kahlua, ananas juice, grenadine', nl: 'Vodka, Archers, Kahlua, ananas sap, grenadine', de: 'Wodka, Archers, Kahlua, Ananas Saft, grenadine'},price:''},
{category:'sexycocktails',name:{tr: 'Virgin Kiss', en: 'Virgin Kiss', ru: 'Невинный поцелуй', dk: 'Virgin Kiss', fi: 'Virgin Kiss', se: 'Virgin Kiss', no: 'Virgin Kiss', nl: 'Virgin Kiss', de: 'Virgin Kiss'},desc:{tr: 'Bacardi, muz likörü, portakal likörü, portakal suyu, grenadin', en: 'Bacardi, banana liqueur, orange liqueur, orange juice, grenadine', ru: 'Bacardi, банановый ликер, апельсиновый ликер, апельсиновый сок, гренадин', dk: 'Bacardi, banan liqueur, appelsin liqueur, appelsin juice, grenadine', fi: 'Bacardi, banaani liqueur, appelsiini liqueur, appelsiini mehu, grenadine', se: 'Bacardi, banan liqueur, apelsin liqueur, apelsin juice, grenadine', no: 'Bacardi, banan liqueur, appelsin liqueur, appelsin juice, grenadine', nl: 'Bacardi, banaan liqueur, sinaasappel liqueur, sinaasappel sap, grenadine', de: 'Bacardi, Banane liqueur, Orange liqueur, Orange Saft, grenadine'},price:''},
{category:'sexycocktails',name:{tr: 'Love Me', en: 'Love Me', ru: 'Люби меня', dk: 'Love Me', fi: 'Love Me', se: 'Love Me', no: 'Love Me', nl: 'Love Me', de: 'Love Me'},desc:{tr: 'Cin, Bacardi, Malibu, tekila, limon suyu, grenadin', en: 'Gin, Bacardi, Malibu, tequila, lemon juice, grenadine', ru: 'Джин, Bacardi, Malibu, текила, лимонный сок, гренадин', dk: 'Gin, Bacardi, Malibu, tequila, citron juice, grenadine', fi: 'Gin, Bacardi, Malibu, tequila, sitruuna mehu, grenadine', se: 'Gin, Bacardi, Malibu, tequila, citron juice, grenadine', no: 'Gin, Bacardi, Malibu, tequila, sitron juice, grenadine', nl: 'Gin, Bacardi, Malibu, tequila, citroen sap, grenadine', de: 'Gin, Bacardi, Malibu, Tequila, Zitrone Saft, grenadine'},price:''},
{category:'sexycocktails',name:{tr: 'Gin Fizz', en: 'Gin Fizz', ru: 'Джин Физз', dk: 'Gin Fizz', fi: 'Gin Fizz', se: 'Gin Fizz', no: 'Gin Fizz', nl: 'Gin Fizz', de: 'Gin Fizz'},desc:{tr: 'Cin, limon suyu, şeker, maden suyu', en: 'Gin, lemon juice, sugar, mineral water', ru: 'Джин, лимонный сок, сахар, минеральная вода', dk: 'Gin, citron juice, sugar, mineral water', fi: 'Gin, sitruuna mehu, sugar, mineral water', se: 'Gin, citron juice, sugar, mineral water', no: 'Gin, sitron juice, sugar, mineral water', nl: 'Gin, citroen sap, sugar, mineral water', de: 'Gin, Zitrone Saft, sugar, mineral water'},price:''},
{category:'sexycocktails',name:{tr: 'Perfect Kiss', en: 'Perfect Kiss', ru: 'Идеальный поцелуй', dk: 'Perfect Kiss', fi: 'Perfect Kiss', se: 'Perfect Kiss', no: 'Perfect Kiss', nl: 'Perfect Kiss', de: 'Perfect Kiss'},desc:{tr: 'Bacardi, şeftali likörü, kırılmış buz, Sprite', en: 'Bacardi, peach liqueur, crushed ice, sprite', ru: 'Bacardi, персиковый ликер, дробленый лед, Sprite', dk: 'Bacardi, peach liqueur, crushed is, Sprite', fi: 'Bacardi, peach liqueur, crushed jää, Sprite', se: 'Bacardi, peach liqueur, crushed is, Sprite', no: 'Bacardi, peach liqueur, crushed is, Sprite', nl: 'Bacardi, peach liqueur, crushed ijs, Sprite', de: 'Bacardi, peach liqueur, crushed Eis, Sprite'},price:''},
{category:'sexycocktails',name:{tr: 'Sex Red', en: 'Sex Red', ru: 'Красный секс', dk: 'Sex Red', fi: 'Sex Red', se: 'Sex Red', no: 'Sex Red', nl: 'Sex Red', de: 'Sex Red'},desc:{tr: 'Jägermeister, taze limon suyu, Sprite, meyve suyu, buz', en: 'Jägermeister, fresh lemon juice, sprite, fruit juice, ice', ru: 'Jägermeister, свежий лимонный сок, Sprite, фруктовый сок, лед', dk: 'Jägermeister, frisk citron juice, Sprite, fruit juice, is', fi: 'Jägermeister, tuore sitruuna mehu, Sprite, fruit mehu, jää', se: 'Jägermeister, färsk citron juice, Sprite, fruit juice, is', no: 'Jägermeister, fersk sitron juice, Sprite, fruit juice, is', nl: 'Jägermeister, vers citroen sap, Sprite, fruit sap, ijs', de: 'Jägermeister, frisch Zitrone Saft, Sprite, fruit Saft, Eis'},price:''},
{category:'sexycocktails',name:{tr: 'Blue Drink', en: 'Blue Drink', ru: 'Голубой напиток', dk: 'Blå Drink', fi: 'Sininen Drink', se: 'Blå Drink', no: 'Blå Drink', nl: 'Blauw Drink', de: 'Blau Drink'},desc:{tr: 'Blue Curaçao, votka, Bacardi, taze limon suyu, Sprite', en: 'Blue Curaçao, vodka, Bacardi, fresh lemon juice, sprite', ru: 'Blue Curaçao, водка, Bacardi, свежий лимонный сок, Sprite', dk: 'Blå Curaçao, vodka, Bacardi, frisk citron juice, Sprite', fi: 'Sininen Curaçao, vodka, Bacardi, tuore sitruuna mehu, Sprite', se: 'Blå Curaçao, vodka, Bacardi, färsk citron juice, Sprite', no: 'Blå Curaçao, vodka, Bacardi, fersk sitron juice, Sprite', nl: 'Blauw Curaçao, vodka, Bacardi, vers citroen sap, Sprite', de: 'Blau Curaçao, Wodka, Bacardi, frisch Zitrone Saft, Sprite'},price:''},
{category:'sexycocktails',name:{tr: 'Aperol Spritz', en: 'Aperol Spritz', ru: 'Апероль Шприц', dk: 'Aperol Spritz', fi: 'Aperol Spritz', se: 'Aperol Spritz', no: 'Aperol Spritz', nl: 'Aperol Spritz', de: 'Aperol Spritz'},desc:{tr: 'Blue Curaçao', en: 'Blue Curaçao', ru: 'Blue Curaçao', dk: 'Blå Curaçao', fi: 'Sininen Curaçao', se: 'Blå Curaçao', no: 'Blå Curaçao', nl: 'Blauw Curaçao', de: 'Blau Curaçao'},price:''}
  ];

  function render(cat, lang) {
    display.innerHTML = '';
    const items = menu.filter(i => i.category === cat);

    if (items.length === 0) {
      display.innerHTML = `<p style="text-align:center; padding:50px; color:#999;">${lang === 'tr' ? 'Yakında eklenecek...' : lang === 'en' ? 'Coming soon...' : lang === 'ru' ? 'Скоро...' : lang === 'dk' ? 'Kommer snart...' : lang === 'fi' ? 'Tulossa pian...' : lang === 'se' ? 'Kommer snart...' : lang === 'no' ? 'Kommer snart...' : lang === 'nl' ? 'Binnenkort beschikbaar...' : lang === 'de' ? 'Bald verfügbar...' : 'Yakında eklenecek...'}</p>`;
      return;
    }

    items.forEach((i, index) => {
      const div = document.createElement('div');
      div.className = 'menu-item';
      div.setAttribute('data-category', i.category);
      div.innerHTML = `
        <div style="flex:1; padding-right:10px;">
          <h3 class="item-name">${i.name[lang] || i.name.tr}</h3>
          <p class="item-description">${i.desc?.[lang] || i.desc?.tr || ''}</p>
        </div>
        <div class="item-price">${i.price ? i.price + '₺' : '--'}</div>
      `;
      display.appendChild(div);

      setTimeout(() => {
        div.style.opacity = '1';
        div.style.transform = 'translateY(0)';
      }, index * 50);
    });
  }

  categoryButtons.forEach(btn => {
    btn.addEventListener('click', () => {
      categoryButtons.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      btn.scrollIntoView({ behavior: 'smooth', inline: 'center', block: 'nearest' });
      currentCategory = btn.dataset.category;
      render(currentCategory, currentLang);
    });
  });

  updateLanguageSelection(currentLang);

  languageSelectedButton.addEventListener('click', () => {
    languageDropdown.classList.toggle('open');
    const expanded = languageDropdown.classList.contains('open');
    languageSelectedButton.setAttribute('aria-expanded', expanded ? 'true' : 'false');
  });

  languageOptions.forEach(option => {
    option.addEventListener('click', () => {
      const selectedLang = option.dataset.lang;
      updateLanguageSelection(selectedLang);
      document.querySelectorAll('[data-tr]').forEach(el => {
        const translation = el.getAttribute(`data-${selectedLang}`);
        if (translation) el.textContent = translation;
      });
      languageDropdown.classList.remove('open');
      languageSelectedButton.setAttribute('aria-expanded', 'false');
      render(currentCategory, currentLang);
    });
  });

  document.addEventListener('click', (event) => {
    if (!languageDropdown.contains(event.target)) {
      languageDropdown.classList.remove('open');
      languageSelectedButton.setAttribute('aria-expanded', 'false');
    }
  });

  render(currentCategory, currentLang);
});
